#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# AIChE J. 2021;67(11):e17371
# DOI : https://doi.org/10.1002/aic.17371

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

#-- Run on single processor
runApplication `getApplication`

# Post-process
# multiRegionPotentialFoam -postProcess -func surfaces -latestTime -region electrolyte
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
